### ISSUE TITLE
Build fail on CH32V303 because of USB enum

### ISSUE THREAD

**Issue by romainreignier** [ch32-rs/ch32-hal#57]
Hi,
I have updated [ch32-hal-template](https://github.com/ch32-rs/ch32-hal-template) to follow the changes here but the CI fails to build for the CH32V30**3** target while it builds the V30**5** and V30**7**:

```
cannot find type `USBHD` in module `crate::interrupt::typelevel`
```
See here: https://github.com/ch32-rs/ch32-hal-template/actions/runs/11609866471/job/32328005840#step:8:147

@Codetector1374 or @andelf you might be quicker than me to find the issue.
I guess it might be something in ch32-data.

**Comment by romainreignier** [comment]
Thanks

**Comment by andelf** [comment]
lol, now I need to fix ch32v208 irq signals
